[project]
name = "nltcache"
version = "1.0.6"
description = "nltcache"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [ "cachebox==5.0.1", "diskcache>=5.6.3", "nltlog>=1.0.9",]
[[project.authors]]
name = "niuliangtao"
email = "farfarfun@qq.com"

[tool.setuptools]
license-files = []
